<?php 
/*
Plugin Name: Aspire Subscribers
Plugin URI: aspireitsolution.com
Description: This plugin  is used for subscription
Version: 0.0.1
Author: Aspire It Solution
Author URI: aspireitsolution.com
Text Domain: as
Generated By: http://ensuredomains.com
*/

// If this file is called directly, abort. //

/*
* Db Create 
*
*/

function subscribers_on_activation(){
  // create the custom table
  global $wpdb;
  
  $table_name = $wpdb->prefix . 'email_subscribers';
  $charset_collate = $wpdb->get_charset_collate();
  $sql = "CREATE TABLE $table_name (
    id mediumint(9) NOT NULL AUTO_INCREMENT,
    user_id int(11) NOT NULL,
    url varchar(55) DEFAULT '' NOT NULL,
    email_address varchar(250) NOT NULL,
    status int(11) NOT NULL,
    percentage_amount int(11) NOT NULL,
    created_at datetime DEFAULT '0000-00-00 00:00:00' NOT NULL,
    updated_at datetime DEFAULT '0000-00-00 00:00:00' NOT NULL,
    PRIMARY KEY  (id)
  ) $charset_collate;";

  require_once( ABSPATH . 'wp-admin/includes/upgrade.php' );
  dbDelta( $sql );
}
register_activation_hook( __FILE__, 'subscribers_on_activation' );


if ( ! defined( 'WPINC' ) ) {die;} // end if

// Let's Initialize Everything
if ( file_exists( plugin_dir_path( __FILE__ ) . 'core-init.php' ) ) {
require_once( plugin_dir_path( __FILE__ ) . 'core-init.php' );
}


